### ISSUE TITLE
extend Image.set_channel_stokes for computed polarization components

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#51]
The "Stokes" slider in the animator widget has been generalized to "Polarization" to include other non-Stokes polarization components. The full "Stokes" enums (table 29 of https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf) is

![Screen Shot 2022-09-08 at 09 30 44](https://user-images.githubusercontent.com/20819712/189013656-f8008268-eb04-42bf-a505-a7ddd10a20cb.png)

In addition to the above components, CARTA internally generates "computed" components from Stokes IQUV including
- Ptotal
- Plinear
- PFtotal
- PFlinear
- Pangle
The exact list of the computed components depends on the integrity of Stokes IQUV. For example, if Stokes I is missing, fractional ones are not included. The protobuf enums can be found at https://carta-protobuf.readthedocs.io/en/latest/enums.html#polarizationtype

![Screen Shot 2022-09-08 at 09 41 52](https://user-images.githubusercontent.com/20819712/189014857-b8a8c676-70a1-4b1c-a0a9-19764593b769.png)

I suggest we also change `set_channel_stokes` to `set_channel_polarization` for consistency. Relevant "stokes" variables in the codebase may need to be revised too for better readability. 

One minor issue about the validation of the stokes:
if we load a IQUV cube and do
`img0.set_channel_stokes(55, 4, recursive=True)`
an exception occurs
```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/validation.py", line 615, in newfunc
    param.validate(value, self)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/validation.py", line 559, in validate
    param.validate(value, parent)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/validation.py", line 152, in validate
    raise ValueError(f"{value} is greater than or equal to maximum value {self.max}.")
ValueError: 4 is greater than or equal to maximum value 4.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kswang/carta_pythonInterface_testing/test.py", line 13, in <module>
    img0.set_channel_stokes(55, 4, recursive=True)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/validation.py", line 628, in newfunc
    raise CartaValidationFailed(f"Invalid function parameter: {msg}")
carta.util.CartaValidationFailed: Invalid function parameter: 4 is greater than or equal to maximum value 4.
```
I think this is the classic 0-based/1-based index issue. `ValueError: 4 is greater than or equal to maximum value 4.` should be `ValueError: 4 is greater than or equal to maximum value 3.` (NOTE: here the computed components are not considered. This is what it does in the current codebase).

**Comment by confluence** [comment]
Here's what I think is required for this:

1. You're right about the bug in the current codebase; the validation for that argument is wrong. It's currently `Evaluate(Number, 0, Attr("num_stokes"), Number.INCLUDE_MIN)`, and it should be `Evaluate(Number, 1, Attr("num_stokes"))`. This is a helper class which constructs the object which is used for validating the parameter at runtime using the available Stokes.
2. Agreed; this function should be renamed. The word Stokes currently appears only in a couple of places in `image.py`. Would we still keep `num_stokes` for the number of basic Stokes?
3. There should be a new `Polarization` "constant" class in `constants.py`, which copies the mappings from the `POLARIZATIONS` enum in the frontend (not the protobuf enum). I suggest using full names for the computed polarizations. This is not going to be used directly for validation (because we have to check at runtime if a polarization is available); it's for the user to be able to enter named keywords like `Polarization.Q` or `Polarization.POLARIZED_INTENSITY` instead of raw integers.
4. For the validation, we will need a new attribute on the image class for the available polarizations. I believe that the `polarizations` action in the frontend's frame store returns a list of polarizations (as integers), which is exactly what we need. We would add a method which calls this action, and use the `@property` and `@cached` decorators to 1) turn it into an attribute, and 2) cache the result for future accesses to use. The actual `@validate` decorator parameter for this argument would probably be something like `Evaluate(OneOf, Attr("polarizations"))` -- that constructs a `OneOf` validator class (which checks for membership in an iterable) at runtime using the new attribute which lists the available polarizations.
5. To allow the user to query polarizations using the keyword names, I also suggest adding a `has_polarization` method which checks the argument against the `polarizations` attribute. This method *would* just use the `Polarization` class directly for validation (`@validate(Constant(Polarization))`).
6. Docstrings for methods with validation should have placeholders where the validation classes fill in information about the input parameters. You can build the Sphinx docs locally to check whether they're rendering as expected.
