### ISSUE TITLE
move bias and contrast from Image.set_colormap to Image.set_scaling?

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#58]
wonder if we should move bias and contrast keyword arguments from Image.set_colormap() to Image.set_scaling()? Effectively when a non-0 bias and a non-1 contrast are applied, the resulting transfer function as seen as a grey curve is a combination of the selected scaling function (eg Square root), the bias function and the contrast function. What do you think?

![Screen Shot 2022-09-21 at 14 18 35](https://user-images.githubusercontent.com/20819712/191429158-f4bb31e3-e06a-4cf9-bbdb-6b625c44f1a9.png)

**Comment by confluence** [comment]
Sounds sensible. We'll need to consider the logic around resetting the bias and contrast values (currently they're reset when the colourmap changes, which is not what the GUI does, and we should drop that). `set_scaling` should accept the special `AUTO` value (which is being added in #79) and handle it by calling the appropriate reset function. The `scaling` parameter to `set_scaling` should also be optional, so that the function can be used to change the scaling options without changing the scaling function, and the function-specific parameters should probably be set regardless of what the function is.

**Comment by I-Chenn** [comment]
> Sounds sensible. We'll need to consider the logic around resetting the bias and contrast values (currently they're reset when the colourmap changes, which is not what the GUI does, and we should drop that). `set_scaling` should accept the special `AUTO` value (which is being added in #79) and handle it by calling the appropriate reset function.

To accept the `AUTO` value, we need that `Auto` constant validator created in #79. Since #79 is still being postponed, is it proper to create that `Auto` validator here and deal with the conflict later when #79 is merged?
