### ISSUE TITLE
do we need to provide Image.set_raster_visible() to users?

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#61]
based on 
![Screen Shot 2022-10-03 at 15 55 22](https://user-images.githubusercontent.com/20819712/193527447-a15a4f31-d8a4-4eac-a837-926fbc7a577f.png)

users can actually call Image.set_raster_visible() to show or hide a raster image. But users can also use Image.show_raster() or Image.hide_raster() for the same purpose. Maybe we can just choose a side to reduce the redundancy here. Or we keep the way it is now but _hide_ Image.set_raster_visible() from users.

**Comment by confluence** [comment]
This is an intentional part of the API, and a similar pattern is followed for other functions. The `show_` and `hide_` functions are made available as aliases to `set_***_visible`  for convenience and user-friendliness, but the underlying functions are also required because the user may have a boolean value. It depends on how the user's code is structured; I think that both are valid uses of the API.

**Comment by confluence** [comment]
I'm going to close this for now; we can reopen the more general issue of this convention after the API refactoring, if we want to.
